### ISSUE TITLE
This is messing up folder permissions.

### ISSUE THREAD

**Issue by Botspot** [Jai-JAP/pikiss-gui#3]
I was unable to download Minecraft Pi (modded)'s AppImage to the `~/.local/bin` folder because that folder was owned by `root`. Why was it owned by root? Well this folder gives a clue: `~/.local/bin/pikiss-gui` It's also owned by root.

To reproduce:

1. First uninstall PiKISS-GUI
2. Remove the ~/.local/bin folder. This is important because a fresh image of RPiOS does not have this folder.
3. Install PiKISS-GUI and notice that it has created the `~/.local/bin/pikiss-gui` folder, and the parent folder, `~/.local/bin`, both being owned by root, rather than by the current `$USER`.

Please fix this.

**Comment by TheBrokenRail** [comment]
Quick look revealed it's because `ninja -C build install` is called with `sudo` (https://github.com/Jai-JAP/pikiss-gui/blob/b189ad0c233604c0749301716c2be257009c594a/build.sh#L4).

**Comment by Jai-JAP** [comment]
@Botspot this should be fixed now. Can you try again...

**Comment by Botspot** [comment]
Now when installing PiKISS-GUI it gives me this error:
```
Syncing Apps with PiKISS...


su: user /home/pi/.local/share/pikiss-gui/getapps.sh does not exist or the user entry does not contain all the required fields
while executing ['/home/pi/pikiss-gui/post_install.sh']
FAILED: meson-postinst 
/usr/local/bin/meson --internal exe --unpickle /home/pi/pikiss-gui/build/meson-private/meson_exe_post_install.sh_62e6f25bcfa1881bca3f8ac30100fe386b73c23d.dat
ninja: build stopped: subcommand failed.
Failed to build PiKISS GUI
```

**Comment by Jai-JAP** [comment]
Oh.. you need to `chown -R $USER:$USER ~/.local/` and then start the build

**Comment by Jai-JAP** [comment]
@Botspot

**Comment by Botspot** [comment]
Same error after trying your suggestion, @Jai-JAP.

Can you try to reproduce this?

**Comment by Jai-JAP** [comment]
@Botspot I got a different issue & fixed that and now no errors. tested

**Comment by Botspot** [comment]
It works now. Thank you.
